### ISSUE TITLE
Docs hosted online

### ISSUE THREAD

**Issue by alekzvik** [ajford/flask-sendmail#2]
Hi, 
What about docs? Can you make them available online?
The great option here is http://readthedocs.org.
Link to quickstart: http://read-the-docs.readthedocs.org/en/latest/getting_started.html

**Comment by ajford** [comment]
Done. Had planned on using PyPI, but hadn't yet figured out how. I've never published anything to PyPI before.

Docs are now online at http://flask-sendmail.readthedocs.org

**Comment by alekzvik** [comment]
Great work!

Here is pretty nice tutorial on PyPI:
http://diveintopython3.ep.io/packaging.html

**Comment by alekzvik** [comment]
And there is another one from Tarek Ziade:
http://guide.python-distribute.org/quickstart.html
