### ISSUE TITLE
Error, when tests run

### ISSUE THREAD

**Issue by alekzvik** [ajford/flask-sendmail#5]
When I run `python setup.py test` all tests pass, but then I get following error.

``` bash
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 284, in _exit_function
    info('process shutting down')
TypeError: 'NoneType' object is not callable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 284, in _exit_function
    info('process shutting down')
TypeError: 'NoneType' object is not callable
```

**Comment by alekzvik** [comment]
Error appears on Python 2.6 and Python 2.7.
All tests pass in Python 2.5 without error.

**Comment by ajford** [comment]
I'm unable to tell what this is. As far as I can tell, its some issue with nose 1.1.2 and being called by something else (see https://groups.google.com/d/topic/nose-users/fnJ-kAUbYHQ/discussion )

If you call `nosetests tests.py` directly, you don't get those errors, and if you install nose 1.0.0, the errors don't surface either. 

I'll keep digging, but I'm not sure what's causing the problem.

**Comment by mitar** [comment]
It is this bug: http://bugs.python.org/issue15881

There is also a workaround described.
